; Injection queries for Lex — Zed flavour.
;
; GENERATED by scripts/gen-injections.py — do not edit by hand. To add a
; language, edit LANGUAGES in that script and re-run it.
;
; Verbatim blocks closed with a recognised language annotation get that
; language injected into their content. Zed's documented injection
; predicates are #set! / #eq?; the upstream tree-sitter-lex
; injections.scm relies on #gsub! to extract the first word from a
; potentially-parametrised header (e.g. ":: json format=pretty ::"),
; which Zed does not support. We instead enumerate each
; (language × content-type) pair explicitly.
;
; Tree-sitter parses verbatim content as paragraph / definition / list /
; session / table_row / verbatim_content depending on what the bytes
; look like — Python's ":" lines look like definitions, list-marker
; lines look like lists, and so on. All variants must be matched so
; users don't lose injection on real code.
;
; The "table" annotation is intentionally absent: table contents are
; lex with inline syntax, not a foreign language.


; --- python (python) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(python)\\b")
 (#set! injection.language "python")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(python)\\b")
 (#set! injection.language "python")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(python)\\b")
 (#set! injection.language "python")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(python)\\b")
 (#set! injection.language "python")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(python)\\b")
 (#set! injection.language "python")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(python)\\b")
 (#set! injection.language "python")
 (#set! injection.combined))


; --- json (json) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(json)\\b")
 (#set! injection.language "json")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(json)\\b")
 (#set! injection.language "json")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(json)\\b")
 (#set! injection.language "json")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(json)\\b")
 (#set! injection.language "json")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(json)\\b")
 (#set! injection.language "json")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(json)\\b")
 (#set! injection.language "json")
 (#set! injection.combined))


; --- javascript (javascript, js) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(javascript|js)\\b")
 (#set! injection.language "javascript")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(javascript|js)\\b")
 (#set! injection.language "javascript")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(javascript|js)\\b")
 (#set! injection.language "javascript")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(javascript|js)\\b")
 (#set! injection.language "javascript")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(javascript|js)\\b")
 (#set! injection.language "javascript")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(javascript|js)\\b")
 (#set! injection.language "javascript")
 (#set! injection.combined))


; --- typescript (typescript, ts) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(typescript|ts)\\b")
 (#set! injection.language "typescript")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(typescript|ts)\\b")
 (#set! injection.language "typescript")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(typescript|ts)\\b")
 (#set! injection.language "typescript")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(typescript|ts)\\b")
 (#set! injection.language "typescript")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(typescript|ts)\\b")
 (#set! injection.language "typescript")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(typescript|ts)\\b")
 (#set! injection.language "typescript")
 (#set! injection.combined))


; --- rust (rust) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(rust)\\b")
 (#set! injection.language "rust")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(rust)\\b")
 (#set! injection.language "rust")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(rust)\\b")
 (#set! injection.language "rust")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(rust)\\b")
 (#set! injection.language "rust")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(rust)\\b")
 (#set! injection.language "rust")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(rust)\\b")
 (#set! injection.language "rust")
 (#set! injection.combined))


; --- go (go) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(go)\\b")
 (#set! injection.language "go")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(go)\\b")
 (#set! injection.language "go")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(go)\\b")
 (#set! injection.language "go")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(go)\\b")
 (#set! injection.language "go")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(go)\\b")
 (#set! injection.language "go")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(go)\\b")
 (#set! injection.language "go")
 (#set! injection.combined))


; --- shellscript (bash, shell, sh, zsh) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(bash|shell|sh|zsh)\\b")
 (#set! injection.language "shellscript")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(bash|shell|sh|zsh)\\b")
 (#set! injection.language "shellscript")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(bash|shell|sh|zsh)\\b")
 (#set! injection.language "shellscript")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(bash|shell|sh|zsh)\\b")
 (#set! injection.language "shellscript")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(bash|shell|sh|zsh)\\b")
 (#set! injection.language "shellscript")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(bash|shell|sh|zsh)\\b")
 (#set! injection.language "shellscript")
 (#set! injection.combined))


; --- yaml (yaml) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(yaml)\\b")
 (#set! injection.language "yaml")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(yaml)\\b")
 (#set! injection.language "yaml")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(yaml)\\b")
 (#set! injection.language "yaml")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(yaml)\\b")
 (#set! injection.language "yaml")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(yaml)\\b")
 (#set! injection.language "yaml")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(yaml)\\b")
 (#set! injection.language "yaml")
 (#set! injection.combined))


; --- toml (toml) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(toml)\\b")
 (#set! injection.language "toml")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(toml)\\b")
 (#set! injection.language "toml")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(toml)\\b")
 (#set! injection.language "toml")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(toml)\\b")
 (#set! injection.language "toml")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(toml)\\b")
 (#set! injection.language "toml")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(toml)\\b")
 (#set! injection.language "toml")
 (#set! injection.combined))


; --- html (html) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(html)\\b")
 (#set! injection.language "html")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(html)\\b")
 (#set! injection.language "html")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(html)\\b")
 (#set! injection.language "html")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(html)\\b")
 (#set! injection.language "html")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(html)\\b")
 (#set! injection.language "html")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(html)\\b")
 (#set! injection.language "html")
 (#set! injection.combined))


; --- css (css) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(css)\\b")
 (#set! injection.language "css")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(css)\\b")
 (#set! injection.language "css")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(css)\\b")
 (#set! injection.language "css")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(css)\\b")
 (#set! injection.language "css")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(css)\\b")
 (#set! injection.language "css")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(css)\\b")
 (#set! injection.language "css")
 (#set! injection.combined))


; --- sql (sql) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(sql)\\b")
 (#set! injection.language "sql")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(sql)\\b")
 (#set! injection.language "sql")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(sql)\\b")
 (#set! injection.language "sql")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(sql)\\b")
 (#set! injection.language "sql")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(sql)\\b")
 (#set! injection.language "sql")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(sql)\\b")
 (#set! injection.language "sql")
 (#set! injection.combined))


; --- markdown (markdown, md) ---

((verbatim_block
  (paragraph) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(markdown|md)\\b")
 (#set! injection.language "markdown")
 (#set! injection.combined))

((verbatim_block
  (definition) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(markdown|md)\\b")
 (#set! injection.language "markdown")
 (#set! injection.combined))

((verbatim_block
  (list) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(markdown|md)\\b")
 (#set! injection.language "markdown")
 (#set! injection.combined))

((verbatim_block
  (session) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(markdown|md)\\b")
 (#set! injection.language "markdown")
 (#set! injection.combined))

((verbatim_block
  (table_row) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(markdown|md)\\b")
 (#set! injection.language "markdown")
 (#set! injection.combined))

((verbatim_block
  (verbatim_content) @injection.content
  (annotation_header) @_lang)
 (#match? @_lang "^\\s*(markdown|md)\\b")
 (#set! injection.language "markdown")
 (#set! injection.combined))

