#!/usr/bin/env python3
"""Generate languages/lex/injections.scm from a flat language table.

Zed's documented injection-query predicates are #set! / #eq?, with no
support for #gsub! to extract a sub-string from a captured node. Lex's
annotation_header is a single node containing the full label (often with
parameters: ":: json format=pretty ::"), so we can't directly capture
the language name. We emit one pattern per (language × content-type)
combination instead.

Run after editing LANGUAGES below, then commit the resulting injections.scm.
A bats test asserts the file matches what this script would produce.
"""
from __future__ import annotations

from pathlib import Path
import sys

# (zed_language_id, [annotation_aliases]).  zed_language_id must match
# Zed's language ID exactly (typically lowercase). Aliases are matched
# against the raw annotation_header text via #match? on a regex like
# "^\\s*(alias1|alias2)\\b".
LANGUAGES: list[tuple[str, list[str]]] = [
    ("python",      ["python"]),
    ("json",        ["json"]),
    ("javascript",  ["javascript", "js"]),
    ("typescript",  ["typescript", "ts"]),
    ("rust",        ["rust"]),
    ("go",          ["go"]),
    ("shellscript", ["bash", "shell", "sh", "zsh"]),
    ("yaml",        ["yaml"]),
    ("toml",        ["toml"]),
    ("html",        ["html"]),
    ("css",         ["css"]),
    ("sql",         ["sql"]),
    ("markdown",    ["markdown", "md"]),
]

# Verbatim content can be parsed as any of these block types because
# tree-sitter doesn't know it's verbatim until the closing annotation.
# Match all of them so injections work for arbitrary embedded content.
CONTENT_TYPES = [
    "paragraph",
    "definition",
    "list",
    "session",
    "table_row",
    "verbatim_content",
]

HEADER = """\
; Injection queries for Lex — Zed flavour.
;
; GENERATED by scripts/gen-injections.py — do not edit by hand. To add a
; language, edit LANGUAGES in that script and re-run it.
;
; Verbatim blocks closed with a recognised language annotation get that
; language injected into their content. Zed's documented injection
; predicates are #set! / #eq?; the upstream tree-sitter-lex
; injections.scm relies on #gsub! to extract the first word from a
; potentially-parametrised header (e.g. ":: json format=pretty ::"),
; which Zed does not support. We instead enumerate each
; (language × content-type) pair explicitly.
;
; Tree-sitter parses verbatim content as paragraph / definition / list /
; session / table_row / verbatim_content depending on what the bytes
; look like — Python's ":" lines look like definitions, list-marker
; lines look like lists, and so on. All variants must be matched so
; users don't lose injection on real code.
;
; The "table" annotation is intentionally absent: table contents are
; lex with inline syntax, not a foreign language.
"""


def render() -> str:
    out = [HEADER]
    # Tree-sitter query strings escape backslashes the same way C strings
    # do, so the regex `\s*` must appear in the file as `\\s*`. Python's
    # source-level escapes are independent — we want a literal pair of
    # backslashes, so we double them again here.
    BS2 = "\\\\"  # a single literal "\\" in the output
    for lang_id, aliases in LANGUAGES:
        regex = f"^{BS2}s*(" + "|".join(aliases) + f"){BS2}b"
        out.append(f"\n; --- {lang_id} ({', '.join(aliases)}) ---")
        for ct in CONTENT_TYPES:
            out.append(
                f"\n((verbatim_block\n"
                f"  ({ct}) @injection.content\n"
                f"  (annotation_header) @_lang)\n"
                f' (#match? @_lang "{regex}")\n'
                f' (#set! injection.language "{lang_id}")\n'
                f" (#set! injection.combined))"
            )
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    target = Path(__file__).resolve().parent.parent / "languages" / "lex" / "injections.scm"
    new = render()
    if "--check" in sys.argv:
        current = target.read_text() if target.exists() else ""
        if current != new:
            print(
                f"FAIL: {target} is out of sync with gen-injections.py.\n"
                f"      Run: python3 scripts/gen-injections.py",
                file=sys.stderr,
            )
            return 1
        print(f"  ✓ {target.name} matches generator")
        return 0
    target.write_text(new)
    print(f"wrote {target} ({len(LANGUAGES)} languages × {len(CONTENT_TYPES)} content types)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
